<a href="https://colab.research.google.com/github/AkhilVinayakp/HAR_LSTM_CNN/blob/main/inp_pipe/inp_pipeline_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.utils import to_categorical

In [ ]:
%cd /content/drive/My\ Drive/datasets 
%pwd

/content/drive/My Drive/datasets


'/content/drive/My Drive/datasets'

In [ ]:

df =  pd.read_csv('inter_norm_mini.csv')

In [ ]:
df.head()

user    activity        timestamp    x-axis    y-axis    z-axis
0    14  Downstairs   57725432324000  0.668528  0.725448 -0.163691
1     7    Upstairs  208866321473000  0.454967  0.875538 -0.162600
2    29     Jogging                0  0.287281  0.887311 -0.360761
3    15     Jogging                0  0.944283  0.292972 -0.149990
4     8     Jogging  111020251899000 -0.124547 -0.706035 -0.697139

In [ ]:
df.drop('user', inplace=True, axis=1)

In [ ]:
df.drop('timestamp', inplace=True, axis=1)

In [ ]:
df

activity    x-axis    y-axis    z-axis
0    Downstairs  0.668528  0.725448 -0.163691
1      Upstairs  0.454967  0.875538 -0.162600
2       Jogging  0.287281  0.887311 -0.360761
3       Jogging  0.944283  0.292972 -0.149990
4       Jogging -0.124547 -0.706035 -0.697139
..          ...       ...       ...       ...
105  Downstairs  0.449064  0.893440 -0.010313
106  Downstairs -0.157978  0.929553  0.333128
107     Jogging  0.687072  0.721425 -0.086476
108     Walking  0.927688  0.373049 -0.015133
109     Walking  0.444785  0.834132 -0.326175

[110 rows x 4 columns]

In [ ]:
df.activity = df.activity.astype('category')
df.activity = df.activity.cat.codes.astype('float64')

In [ ]:
df

activity    x-axis    y-axis    z-axis
0         0.0  0.668528  0.725448 -0.163691
1         4.0  0.454967  0.875538 -0.162600
2         1.0  0.287281  0.887311 -0.360761
3         1.0  0.944283  0.292972 -0.149990
4         1.0 -0.124547 -0.706035 -0.697139
..        ...       ...       ...       ...
105       0.0  0.449064  0.893440 -0.010313
106       0.0 -0.157978  0.929553  0.333128
107       1.0  0.687072  0.721425 -0.086476
108       5.0  0.927688  0.373049 -0.015133
109       5.0  0.444785  0.834132 -0.326175

[110 rows x 4 columns]

In [ ]:
df.dtypes

activity    float64
x-axis      float64
y-axis      float64
z-axis      float64
dtype: object

In [ ]:
dataset = tf.data.Dataset.from_tensor_slices(df)

In [ ]:
window_size = 20

In [ ]:
def enc(y):
  return y+1

In [ ]:
# dataset = dataset.batch(20, drop_remainder=True)
dataset = tf.data.Dataset.from_tensor_slices(df)
dataset = dataset.window(20,shift=10, drop_remainder=True)
dataset = dataset.flat_map(lambda window : window.batch(20))
dataset = dataset.map(lambda window: (window[:,1:],window[:,0]))
dataset = dataset.map(lambda x, y : x , enc(y))

NameError: ignored

In [ ]:
type(dataset)

tensorflow.python.data.ops.dataset_ops.MapDataset

In [ ]:
for window in dataset:
  print(window.numpy())

AttributeError: ignored

In [ ]:
for 


In [ ]:
# test datset
sr = np.arange(0,50)
sr = sr.reshape(10,5)

In [ ]:
sr_set = tf.data.Dataset.from_tensor_slices(sr)

In [ ]:
for s in sr_set.as_numpy_iterator():
  print(s)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]
[20 21 22 23 24]
[25 26 27 28 29]
[30 31 32 33 34]
[35 36 37 38 39]
[40 41 42 43 44]
[45 46 47 48 49]
