In [4]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
%cd /content/drive/My\ Drive/datasets 
%pwd

/content/drive/My Drive/datasets


'/content/drive/My Drive/datasets'

In [5]:
df =  pd.read_csv('mini.csv')

In [6]:
df.head()

user    activity  x-axis  y-axis  z-axis
0    14  Downstairs   17.97   19.50   -4.40
1     7    Upstairs    2.91    5.60   -1.04
2    29     Jogging    0.00    0.00    0.00
3    15     Jogging    0.00    0.00    0.00
4     8     Jogging   -1.54   -8.73   -8.62

In [9]:
series = df.values

In [10]:
series.shape

(110, 5)

In [47]:
series

array([[14, 'Downstairs', 17.97, 19.5, -4.4],
       [7, 'Upstairs', 2.91, 5.6, -1.04],
       [29, 'Jogging', 0.0, 0.0, 0.0],
       [15, 'Jogging', 0.0, 0.0, 0.0],
       [8, 'Jogging', -1.54, -8.73, -8.62],
       [19, 'Jogging', -6.24, -4.29, 4.99],
       [18, 'Sitting', 5.43, 1.76, 8.39],
       [30, 'Upstairs', 9.72, 1.14, 0.34],
       [28, 'Walking', 2.72, 7.35, 3.2552630000000002],
       [35, 'Walking', 1.14, 9.7, 2.8738932999999998],
       [19, 'Walking', -2.45, 6.36, -0.5],
       [20, 'Jogging', 0.0, 0.0, 0.0],
       [1, 'Jogging', 14.82, 1.14, 5.52],
       [10, 'Upstairs', -5.28, 18.47, 5.94],
       [32, 'Jogging', 0.0, 0.0, 0.0],
       [33, 'Jogging', 5.625203599999999, 9.084772, 6.633109599999999],
       [26, 'Walking', 13.59, 3.64, -2.56],
       [26, 'Jogging', 9.38, -0.99, -6.05],
       [22, 'Walking', -0.69, 15.89, 0.72],
       [14, 'Downstairs', -3.3, 15.43, -3.26],
       [19, 'Upstairs', -12.72, 8.62, 1.84],
       [6, 'Downstairs', 9.15, 12.22, -0.61291

In [31]:
sr = np.arange(0,50)
sr = sr.reshape(10,5)

In [32]:
sr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [7]:
def windowed_dataset(series, window_size,shift_size, batch_size,shuffle_buffer):
  dataset = tf.data.Dataset.from_tensor_slices(series)
  dataset = dataset.window(window_size +1, shift = shift_size, drop_remainder = True)
  dataset = dataset.flat_map(lambda window: window.batch(window_size+1))
  dataset = dataset.shuffle(shuffle_buffer).map(lambda window :  (window[:-1], window[-1]))
  dataset = dataset.batch(batch_size).prefetch(1)
  return dataset

In [18]:
# the data often load as batches
# batches can be created by using batch() method
dataset = tf.data.Dataset.range(50)
dataset = dataset.window(6,shift=3, drop_remainder=True)
dataset = dataset.flat_map(lambda window : window.batch(6))
dataset =  dataset.map(lambda window: (window[:-1],window[-1:]))
# shuffling the values
# dataset = dataset.shuffle(buffer_size=40)
# creating the batches
# dataset = dataset.batch(2).prefetch(1) # the value of prefetch ?
# printing out the data
for x, y in dataset:
  print("x = ", x.numpy())
  print("y = ", y.numpy())

x =  [0 1 2 3 4]
y =  [5]
x =  [3 4 5 6 7]
y =  [8]
x =  [ 6  7  8  9 10]
y =  [11]
x =  [ 9 10 11 12 13]
y =  [14]
x =  [12 13 14 15 16]
y =  [17]
x =  [15 16 17 18 19]
y =  [20]
x =  [18 19 20 21 22]
y =  [23]
x =  [21 22 23 24 25]
y =  [26]
x =  [24 25 26 27 28]
y =  [29]
x =  [27 28 29 30 31]
y =  [32]
x =  [30 31 32 33 34]
y =  [35]
x =  [33 34 35 36 37]
y =  [38]
x =  [36 37 38 39 40]
y =  [41]
x =  [39 40 41 42 43]
y =  [44]
x =  [42 43 44 45 46]
y =  [47]


In [34]:
dataset = tf.data.Dataset.from_tensor_slices(sr)
dataset = dataset.window(4,2, drop_remainder= True)
for window_data in dataset:
  for val in window_data:
    print(val.numpy())
  print()

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]

[10 11 12 13 14]
[15 16 17 18 19]
[20 21 22 23 24]
[25 26 27 28 29]

[20 21 22 23 24]
[25 26 27 28 29]
[30 31 32 33 34]
[35 36 37 38 39]

[30 31 32 33 34]
[35 36 37 38 39]
[40 41 42 43 44]
[45 46 47 48 49]



In [35]:
dataset = tf.data.Dataset.from_tensor_slices(sr)
dataset = dataset.window(6,shift=3, drop_remainder=True)
dataset = dataset.flat_map(lambda window : window.batch(6))
for window in dataset:
  print("window data")
  print(window.numpy())

window data
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
window data
[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]]


In [61]:
dataset = tf.data.Dataset.from_tensor_slices(sr)
dataset = dataset.window(6,shift=3, drop_remainder=True)
dataset = dataset.flat_map(lambda window : window.batch(6))
# after creating the window batches use map to map the features and labels
dataset =  dataset.map(lambda window: (window[:,:-1],window[5,4]))
# printing out the data
for x, y in dataset:
  print('x = ',x.numpy(), 'y = ', y.numpy())

x =  [[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]
 [15 16 17 18]
 [20 21 22 23]
 [25 26 27 28]] y =  29
x =  [[15 16 17 18]
 [20 21 22 23]
 [25 26 27 28]
 [30 31 32 33]
 [35 36 37 38]
 [40 41 42 43]] y =  44


In [41]:
r = np.arange(0,25)
r = r.reshape(5,5)

In [44]:
r

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
r[:,2:]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [50]:
r[:,1]

array([ 1,  6, 11, 16, 21])